DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS rating;

CREATE TABLE game (
	gameId INT UNSIGNED AUTO_INCREMENT NOT NULL,
 	gameName VARCHAR(60) NOT NULL,
	UNIQUE(gameName),
	PRIMARY KEY(gameId)
);

CREATE TABLE user (
	userId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	userEmail VARCHAR(128) NOT NULL,
	userLevel SMALLINT(4) UNSIGNED NOT NULL,
	userName VARCHAR(32) NOT NULL,
	userProducts SMALLINT(5) UNSIGNED,
	userReviews SMALLINT(4) UNSIGNED,
	userSalt CHAR(64),
	userHash CHAR(128),
	UNIQUE(userEmail),
	INDEX(userName),
	PRIMARY KEY(userId)
);

CREATE TABLE review (
	reviewId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	gameId INT UNSIGNED NOT NULL,
	userId INT UNSIGNED NOT NULL,
	reviewDate TIMESTAMP,
	reviewRecommendation TINYINT(1) UNSIGNED NOT NULL,
	reviewText VARCHAR(8000) NOT NULL,
	INDEX(gameId),
	INDEX(userId),
	FOREIGN KEY(gameId) REFERENCES game(gameId),
	FOREIGN KEY(userId) REFERENCES user(userId),
	PRIMARY KEY(reviewId)
);

CREATE TABLE comment (
	commentId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	reviewId INT UNSIGNED NOT NULL,
	userId INT UNSIGNED NOT NULL,
	commentDate TIMESTAMP,
	commentText VARCHAR(1000) NOT NULL,
	INDEX(reviewId),
	INDEX(userId),
	FOREIGN KEY(reviewId) REFERENCES review(reviewId),
	FOREIGN KEY(userId) REFERENCES user(userId),
	PRIMARY KEY(commentId)
);

CREATE TABLE rating (
	reviewId INT UNSIGNED NOT NULL,
	userId INT UNSIGNED NOT NULL,
	ratingHelpfulness TINYINT(1) UNSIGNED NOT NULL,
	INDEX(reviewId),
	INDEX(userId),
	FOREIGN KEY(reviewId) REFERENCES review(reviewId),
	FOREIGN KEY(userId) REFERENCES user(userId),
	PRIMARY KEY(reviewId, userId)
);